### ISSUE TITLE
Build error when updating from 2.16.6 to 2.16.7

### ISSUE THREAD

**Issue by finestructure** [dankinsoid/SwiftOpenAPI#3]
Hey @dankinsoid , thanks for providing this nice library to generate the OpenAPI specs!

Not sure if you're aware but we've just run into a compile error when updating from 2.16.6 to 2.16.7:

https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/actions/runs/5220111100/jobs/9422776122?pr=2421

```
❌ /__w/SwiftPackageIndex-Server/SwiftPackageIndex-Server/.build/checkouts/VaporToOpenAPI/Sources/VaporToOpenAPI/AnyValue++.swift:37:3: switch must be exhaustive
                switch self {
                ^
```

I'll try and figure out what the fix might be once I've got a moment but I wanted to let you know right away in case it's an easy fix for you.

**Comment by dankinsoid** [comment]
Hello, @finestructure, you are welcome
I'm sure i'v fixed it in VaporToOpenAPI 4.3.6, which version of VaporToOpenAPI do you use?

**Comment by dankinsoid** [comment]
@finestructure If you use VaporToOpenAPI 3.x, I fixed it at 3.15.2

**Comment by finestructure** [comment]
Ah cheers. I'd run a package update just before but it stayed at "3.15.1", weird.

Let me actually try and move forward to 4.x, I hadn't realised I'm a full major version behind!

**Comment by finestructure** [comment]
Ok, bumping it to 4.x.x fixes it, thanks for your help!
